"""Build the 50-strategy teaching panel used in the README.

The point of a constructed panel is that the answer is known: three of the fifty
strategies are genuinely skilled and the other forty-seven are pure noise, so a
reader can score a hurdle instead of admiring it. Everything is seeded, so the
CSV in this directory is reproducible by re-running this file.

Returns are monthly. Each strategy loads on a common market factor, because the
whole reason the hurdle is bootstrapped rather than read off a table is that
trials are correlated; an independent panel would flatter the method.

Regenerate with:  python examples/make_panel.py
"""
from __future__ import annotations

import math
import os
import random

M = 50                  # strategies tried
T = 240                 # monthly observations (20 years)
N_ALT = 3               # genuinely skilled
SEED = 20260815

# Drifts are set in t units. One strategy is planted well clear of the 5%
# Bonferroni cutoff for m=50 (|t| >= 3.29) and two below it, so the panel shows
# the miss that a per-trial correction buys. These are targets for the expected
# t, not the realised one: the drawn series lands where it lands, and the CSV
# reports whatever that turned out to be.
ALT_T_TARGETS = (4.2, 2.45, 1.95)

SD = 0.04               # monthly vol of the idiosyncratic part
FACTOR_SD = 0.03        # monthly vol of the common factor
BETA_LO, BETA_HI = 0.3, 0.9

HERE = os.path.dirname(os.path.abspath(__file__))
CSV = os.path.join(HERE, "returns_50_strategies.csv")
TRUTH = os.path.join(HERE, "returns_50_strategies.truth.txt")


def build():
    rng = random.Random(SEED)
    factor = [rng.gauss(0.0, FACTOR_SD) for _ in range(T)]
    betas = [rng.uniform(BETA_LO, BETA_HI) for _ in range(M)]

    # The planted strategies are the ones whose index is a multiple of 17, so the
    # truth is not simply "the first three columns".
    alt_idx = [17 * (k + 1) % M for k in range(N_ALT)]

    panel = []
    for j in range(M):
        drift = 0.0
        if j in alt_idx:
            target_t = ALT_T_TARGETS[alt_idx.index(j)]
            # t = mean / (sd / sqrt(T)); solve for the mean that lands on target
            total_sd = math.sqrt((betas[j] * FACTOR_SD) ** 2 + SD ** 2)
            drift = target_t * total_sd / math.sqrt(T)
        series = [drift + betas[j] * factor[t] + rng.gauss(0.0, SD)
                  for t in range(T)]
        panel.append(series)
    return panel, alt_idx


def main():
    panel, alt_idx = build()
    names = [f"strategy_{j:02d}" for j in range(M)]

    with open(CSV, "w", encoding="utf-8", newline="") as fh:
        fh.write(",".join(names) + "\n")
        for t in range(T):
            fh.write(",".join(f"{panel[j][t]:.6f}" for j in range(M)) + "\n")

    with open(TRUTH, "w", encoding="utf-8") as fh:
        fh.write("# Ground truth for returns_50_strategies.csv\n")
        fh.write(f"# {M} strategies, {T} monthly observations, "
                 f"{len(alt_idx)} genuinely skilled.\n")
        fh.write(f"# Generated by make_panel.py, seed {SEED}.\n")
        for j in sorted(alt_idx):
            fh.write(f"{names[j]}\n")

    print(f"wrote {CSV}  ({M} strategies x {T} periods)")
    print(f"wrote {TRUTH}  (skilled: {', '.join(names[j] for j in sorted(alt_idx))})")


if __name__ == "__main__":
    main()
